"""Add categories and subcategories

Revision ID: 50748c94ac18
Revises: 
Create Date: 2025-02-21 08:17:08.300763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50748c94ac18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategory_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'subcategory', ['subcategory_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('subcategory_id')

    # ### end Alembic commands ###
